language: c

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - python
      - cython
      - flex
      - help2man
      - texinfo
      - g++-5

env:
  global:
    - VERBOSE=1 # Get test logs in Travis logs

matrix:
  include:
    - os: linux
      env:
        - COMPILER=g++-5
    - os: osx
      osx_image: xcode9.2
    - compiler: gcc
      env:
        - COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [g++-6]

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python cython flex help2man texinfo ; fi

# Need gettext 0.19, not in trusty; xenial doesn’t seem to work well yet on Travis
install:
  - wget ftp://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.gz
  - tar zxvf gettext-0.19.8.1.tar.gz
  - cd gettext-0.19.8.1 && ./configure && sudo make install && cd ..

script:
  - ./bootstrap
  - ./configure
  - make
  - make distcheck
