language: c

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - python-dbg
      - cython
      - flex
      - help2man
      - texinfo
      - valgrind
      - g++-5

# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: linux
      env:
        - COMPILER=g++-5
        - PYTHON=/usr/bin/python-dbg
        - DISTCHECK_CONFIGURE_FLAGS="PYTHON=/usr/bin/python-dbg"
    - os: osx
      osx_image: xcode9.2
      env:
        - LDFLAGS="-L/usr/local/opt/flex/lib -L/usr/local/opt/texinfo/lib"
        - CPPFLAGS="-I/usr/local/opt/flex/include"
    - compiler: gcc
      env:
        - COMPILER=g++-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [g++-6]

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cython flex help2man texinfo ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/cython/bin:/usr/local/opt/flex/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/gettext/bin:$PATH" ; fi

# Need gettext 0.19, not in trusty; xenial doesn’t seem to work well yet on Travis
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget ftp://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar zxf gettext-0.19.8.1.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd gettext-0.19.8.1 && ./configure --quiet --enable-silent-rules && sudo make install && cd .. ; fi

script:
  - ./bootstrap
  - ./configure --enable-silent-rules
  - make
  - make distcheck
